---
collections:
    development_manual:
        output: true
        layout: default
    installation:
        output: true
        layout: default
    configuration:
        output: true
        layout: default
    user_manual:
        output: true
        layout: default

defaults:
    - scope:
        path: ""
        type: development_manual
      values:
        layout: default
    - scope:
        path: ""
        type: installation
      values:
        layout: default
    - scope:
        path: ""
        type: configuration
      values:
        layout: default
    - scope:
        path: ""
        type: user_manual
      values:
        layout: default
    - scope:
        path: "index.md"
      values:
        layout: default
---  
